version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - ineffassign
    - musttag
    - nilerr
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
